name: flip
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cudatoolkit=11.0.221
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9b
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.1.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.1.2
  - python=3.7.10
  - pytorch=1.7.1
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - black==23.3.0
    - blessings==1.7
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cvxpy==1.1.5
    - cycler==0.11.0
    - cython==0.29.20
    - ecos==2.0.10
    - fonttools==4.34.4
    - gpustat==0.6.0
    - idna==3.3
    - imageio==2.21.0
    - importlib-metadata==6.3.0
    - isort==5.11.5
    - joblib==1.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - kiwisolver==1.4.4
    - matplotlib==3.2.2
    - mpmath==1.1.0
    - mypy-extensions==1.0.0
    - networkx==2.6.3
    - numpy==1.21.6
    - nvidia-ml-py3==7.352.0
    - opencv-python==4.6.0.66
    - osqp==0.6.2.post5
    - packaging==23.0
    - pandas==1.3.5
    - pathspec==0.11.1
    - platformdirs==3.2.0
    - progressbar==2.5
    - psutil==5.9.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==23.2.0
    - qdldl==0.1.5.post2
    - requests==2.28.1
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.4.1
    - scs==3.2.0
    - sklearn==0.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tomli==2.0.1
    - torchfile==0.1.0
    - tornado==6.2
    - tqdm==4.64.0
    - typed-ast==1.5.4
    - typing-extensions==4.5.0
    - urllib3==1.26.11
    - visdom==0.1.8.9
    - websocket-client==1.3.3
    - zipp==3.15.0
